#!/usr/bin/env bash
# Fetch the reviewed Google Fonts set at one immutable upstream commit.
#
#   scripts/fetch-fonts.sh --update-lock  # maintainer: fetch and refresh lock
#   scripts/fetch-fonts.sh                # fetch, then require the committed lock
#   scripts/fetch-fonts.sh --verify-only  # CI/image build: offline verification
#
# Generated files stay in fonts/google/<upstream-path>. Keeping the source path makes
# every licence relationship visible and avoids filename collisions between families.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LIST="$ROOT/fonts/fonts.list"
LOCK="$ROOT/fonts/fonts.lock"
DEST="$ROOT/fonts/google"
LICENCES="$ROOT/fonts/LICENSES.md"
GOOGLE_FONTS_COMMIT="e1118da94a8cb00cf6d06cdac9ef13eb1e5c6ab7"
API="https://api.github.com/repos/google/fonts/contents"

MODE="fetch"
case "${1:-}" in
  "") ;;
  --update-lock) MODE="update" ;;
  --verify-only) MODE="verify" ;;
  *) echo "usage: $0 [--update-lock|--verify-only]" >&2; exit 2 ;;
esac

if [[ ! -f "$LIST" ]]; then
  echo "fetch-fonts: missing $LIST" >&2
  exit 1
fi

hash_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

families() {
  sed -E 's/[[:space:]]*#.*$//' "$LIST" | sed -E '/^[[:space:]]*$/d'
}

verify() {
  if [[ ! -f "$LOCK" ]]; then
    echo "fetch-fonts: missing $LOCK; a maintainer must run --update-lock" >&2
    return 1
  fi

  local failed=0 expected=0 actual=0 source license_count font_count path sum got
  while read -r sum path; do
    [[ -n "${sum:-}" && -n "${path:-}" ]] || continue
    expected=$((expected + 1))
    if [[ ! -f "$ROOT/fonts/$path" ]]; then
      echo "fetch-fonts: missing fonts/$path" >&2
      failed=1
      continue
    fi
    got="$(hash_file "$ROOT/fonts/$path")"
    if [[ "$got" != "$sum" ]]; then
      echo "fetch-fonts: checksum mismatch fonts/$path" >&2
      failed=1
    fi
  done < "$LOCK"

  if [[ -d "$DEST" ]]; then
    actual="$(find "$DEST" -type f | wc -l | tr -d ' ')"
  fi
  if [[ "$actual" -ne "$expected" ]]; then
    echo "fetch-fonts: lock has $expected files but fonts/google has $actual" >&2
    failed=1
  fi

  while IFS= read -r source; do
    license_count="$(find "$DEST/$source" -maxdepth 1 -type f \( -name 'OFL.txt' -o -name 'LICENSE.txt' \) 2>/dev/null | wc -l | tr -d ' ')"
    font_count="$(find "$DEST/$source" -maxdepth 1 -type f -name '*.ttf' 2>/dev/null | wc -l | tr -d ' ')"
    if [[ "$license_count" -ne 1 ]]; then
      echo "fetch-fonts: $source must carry exactly one licence text" >&2
      failed=1
    fi
    if [[ "$font_count" -lt 1 ]]; then
      echo "fetch-fonts: $source has no TTF font" >&2
      failed=1
    fi
  done < <(families)

  [[ "$failed" -eq 0 ]] || return 1
  echo "fetch-fonts: verified $expected files across $(families | wc -l | tr -d ' ') families"
}

if [[ "$MODE" == "verify" ]]; then
  verify
  exit
fi

command -v curl >/dev/null 2>&1 || { echo "fetch-fonts: curl is required" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "fetch-fonts: jq is required" >&2; exit 1; }

STAGE="$(mktemp -d "${TMPDIR:-/tmp}/typst-mcp-fonts.XXXXXX")"
trap 'rm -rf "$STAGE"' EXIT
mkdir -p "$STAGE/google"

while IFS= read -r source; do
  out="$STAGE/google/$source"
  mkdir -p "$out"
  listing="$(curl -fsSL "$API/$source?ref=$GOOGLE_FONTS_COMMIT")"
  count=0
  licence=0
  while IFS=$'\t' read -r name url; do
    [[ -n "$name" && -n "$url" ]] || continue
    case "$name" in
      *.ttf)
        curl -fsSL "$url" -o "$out/$name"
        count=$((count + 1))
        ;;
      OFL.txt|LICENSE.txt)
        curl -fsSL "$url" -o "$out/$name"
        licence=$((licence + 1))
        ;;
    esac
  done < <(jq -r '.[] | [.name, .download_url] | @tsv' <<<"$listing")
  if [[ "$count" -lt 1 || "$licence" -ne 1 ]]; then
    echo "fetch-fonts: $source returned $count fonts and $licence licence texts" >&2
    exit 1
  fi
  echo "fetch-fonts: fetched $source ($count font files)"
done < <(families)

if [[ "$DEST" != "$ROOT/fonts/google" || "$DEST" == "/" ]]; then
  echo "fetch-fonts: refusing unsafe destination $DEST" >&2
  exit 1
fi
rm -rf "$DEST"
mv "$STAGE/google" "$DEST"

if [[ "$MODE" == "update" ]]; then
  : > "$LOCK"
  while IFS= read -r file; do
    rel="${file#"$ROOT/fonts/"}"
    printf '%s  %s\n' "$(hash_file "$file")" "$rel" >> "$LOCK"
  done < <(find "$DEST" -type f | LC_ALL=C sort)

  {
    echo "# Bundled font licences"
    echo
    echo "Generated by \`scripts/fetch-fonts.sh --update-lock\` from Google Fonts commit"
    echo "\`$GOOGLE_FONTS_COMMIT\`. Each family is distributed with the licence text stored"
    echo "beside its font files."
    echo
    echo "| Family source | Licence |"
    echo "|---|---|"
    while IFS= read -r source; do
      licence_path="$(find "$DEST/$source" -maxdepth 1 -type f \( -name 'OFL.txt' -o -name 'LICENSE.txt' \) | head -1)"
      echo "| \`$source\` | \`${licence_path#"$ROOT/fonts/"}\` |"
    done < <(families)
  } > "$LICENCES"
fi

verify
